### ISSUE TITLE
Problem with batch actions routing

### ISSUE THREAD

**Issue by krowek** [marcin-jozwikowski/easy-admin-pretty-urls#31]
Symfony 7.0.2

I found some problem with batch actions (batch delete and custom batch actions)

When I try apply batch action it redirect me to another crud list (probably last) and nothing happen.

For example in PaymentCrudController -> configureActions() I added: 

->addBatchAction(Action::new('merge', 'Merge')
    ->linkToCrudAction('mergePayments')
)

Method mergePayments is defined in PaymentCrudController.

I am on /payments_crud, and after apply batch delete or custom batch action it goes to:

https://domain.com/users_crud/index?crudAction=mergePayments&crudControllerFqcn=App%5CController%5CAdmin%5CPaymentCrudController

users_crud is different CRUD.

The workaround is to add custom controller and use linkToRoute() instead linkToCrudAction() but it is not solution.

**Comment by marcin-jozwikowski** [comment]
Hi,

Thanks for pointing out that problem.

Custom actions are not recognized automatically - they have to be specifically added.

You can do that with `PrettyRoutesController` by listing all actions (up to version 2.4.2) or by listing just the custom actions (starting from 2.5.0).

Those should work for you, depending on the version:
```
#[PrettyRoutesController(customActions: ['mergePayments'])] // 2.5.0 +
#[PrettyRoutesController(actions: ['index', 'new', 'detail', 'edit', 'delete', 'batchDelete', 'renderFilters', 'mergePayments'])] // 2.4.2
class PaymentCrudController {
// ....
}
```

I've also updated the docs so that these options would be better explained than they were. See [here](https://github.com/marcin-jozwikowski/easy-admin-pretty-urls?tab=readme-ov-file#select-actions-to-create-routes-for).

**Comment by krowek** [comment]
@marcin-jozwikowski Great, thank you
