### ISSUE TITLE
Autocomplete endpoint

### ISSUE THREAD

**Issue by Geolim4** [marcin-jozwikowski/easy-admin-pretty-urls#33]
Hello,

I tried to handle the /autocomplete endpoint, but it seems incomptible atm with your bundle, do you know if there's some hardcoded parameters in EA ?

**Comment by marcin-jozwikowski** [comment]
@Geolim4 Ccould you confirm: it about [this](https://symfony.com/bundles/EasyAdminBundle/current/fields/ChoiceField.html#autocomplete) autocomplete feature, right? Or something completely else that I'm unaware of?

**Comment by Geolim4** [comment]
> @Geolim4 Ccould you confirm: it about [this](https://symfony.com/bundles/EasyAdminBundle/current/fields/ChoiceField.html#autocomplete) autocomplete feature, right? Or something completely else that I'm unaware of?

Indeed, its a part of its own controller crud action :D

**Comment by marcin-jozwikowski** [comment]
@Geolim4 I think I have an answer for you, but probably not exactly what you're looking for.
I don't think there's a way to completely shorten the autocomplete URL. You can add the `autocomplete` action to the target controller, but some paramaters sent there will still have to be in query.
i.e. AuthorController if you're looking at the list of authors for your Post - add `#[PrettyRoutesController(customActions: ['autocomplete'])]` as a class Attribute.

The example above, used in [EasyAdmin Demo App](https://github.com/EasyCorp/easyadmin-demo), shortened this:
`http://ea-demo.loc/en/easyadmin?autocompleteContext%5BcrudControllerFqcn%5D=App%5CController%5CEasyAdmin%5CPostCrudController&autocompleteContext%5BpropertyName%5D=author&autocompleteContext%5BoriginatingPage%5D=edit&crudAction=autocomplete&crudControllerFqcn=App%5CController%5CEasyAdmin%5CUserCrudController&page=1&query=`
to this:
`http://ea-demo.loc/user_crud/autocomplete?autocompleteContext%5BcrudControllerFqcn%5D=App%5CController%5CEasyAdmin%5CPostCrudController&autocompleteContext%5BpropertyName%5D=author&autocompleteContext%5BoriginatingPage%5D=edit&page=1&query=`

There is a difference but some params have to be passed via query:

- autocompleteContext[crudControllerFqcn]: App\Controller\EasyAdmin\PostCrudController
- autocompleteContext[propertyName]: author
- autocompleteContext[originatingPage]: edit
- page: 1
- query: 

I will move the `default actions` [list](https://github.com/marcin-jozwikowski/easy-admin-pretty-urls?tab=readme-ov-file#select-actions-to-create-routes-for) to configuration, so that everyone could set them by themselves, and I'll add `autocomplete` to the list of default defaults (I know... but naming is hard). But that will be in couple of days, unfortunately. In the meantime, I'll have to leave you with the solution of adding an Attribute to some of your classes.

**Comment by marcin-jozwikowski** [comment]
@Geolim4 The issue you've raised is addressed in [release v2.6.0](https://github.com/marcin-jozwikowski/easy-admin-pretty-urls/releases/tag/v2.6.0).

**Comment by Geolim4** [comment]
Hello @marcin-jozwikowski that's a great news !
I'll test that tomorrow !

**Comment by Geolim4** [comment]
Working as expected, thanks for the improvement buddy, can be closed 🫶
