### ISSUE TITLE
Pushing the pretty urls to the limits 

### ISSUE THREAD

**Issue by Geolim4** [marcin-jozwikowski/easy-admin-pretty-urls#35]
Hello Marcin,

I want to thank you again for this bundle ! ☺️
Today I wanted to push the pretty urls even further by trying:

```php
    #[PrettyRoutesAction(path: 'modifier/{entityId}')]
    public function edit(AdminContext $context)
    {
        return parent::edit($context);
    }
```

By integrating the entityId straight inside the URLs instead of the current URL query: /edit?entityId=xxxxx

But I encountered a weird error:
`Some mandatory parameters are missing ("entityId") to generate a URL for route "admin_foster_family_crud_edit".`
![image](https://github.com/marcin-jozwikowski/easy-admin-pretty-urls/assets/1332071/de86aa60-0689-4fb9-bc8d-e0a1a59fe6ed)

So you may enlighten me if I'm missing something ?

Have a nice day,
Georges

**Comment by marcin-jozwikowski** [comment]
Honestly I never planned for the routes to take in additional parameters. They were meant to just hide the common params (`easyadmin?crudAction=XXX&crudControllerFqcn=YYY`), but now that I think of it, I cannot remember why nor can I justify that.

I'm not a person to pass on a challenge, so don't loose hope! 😄 

Again, let me get back to you in couple of days.

**Comment by marcin-jozwikowski** [comment]
I'm back with some good news!

Starting from [v2.7.0](https://github.com/marcin-jozwikowski/easy-admin-pretty-urls/releases/tag/v2.7.0) the `entityId` param is (almost) supported by this bundle.
All you'd need to do it to specify a default value for it. In your example it would be:
```
#[PrettyRoutesAction(path: 'modifier/{entityId?0}')]
```

It's unfortunately going to be necessary, since EA generates the 'edit' endpoint URL without providing the ID.  Luckily, the URL of 'modifier/0' will not be visible to the user.

I've also updated the [docs](https://github.com/marcin-jozwikowski/easy-admin-pretty-urls?tab=readme-ov-file#putting-entityid-in-the-path) with this new info.

P.S. @Geolim4 Thanks for this idea. I missed the opportunity to have the ID in path and now you've inspired me to do something about it. I'll make it part of the default configuration for detail, edit, and delete endpoints soon....ish.

**Comment by Geolim4** [comment]
Hello @marcin-jozwikowski that's some nice job here !!
I just hope that EA developer get inspired by your stuff enough to make it native in the next major releases :D


Thanks you again !

**Comment by Geolim4** [comment]
It's working very well, if you're curious I can send you a guest invitation to see how it's working on a real project with a lot of entities. That's impressive !

**Comment by Geolim4** [comment]
Resolved :)

**Comment by marcin-jozwikowski** [comment]
@Geolim4 Sorry for such late reply!

> [...] if you're curious I can send you a guest invitation to see how it's working on a real project [...]

Yes, please! I'd very much like to see it working.

**Comment by Geolim4** [comment]
Alright, I will add you to the repo !

**Comment by Geolim4** [comment]
Added you !
